Add minikube setup and dummy helm commands to CICD

diff --git a/.github/workflows/helm-release.yml b/.github/workflows/helm-release.yml
--- a/.github/workflows/helm-release.yml
+++ b/.github/workflows/helm-release.yml
@@ -3,7 +3,7 @@ name: Release Charts
 on:
   push:
     branches:
-      - main
+      - TECH-2871-improve-cicd-chartss
 
 jobs:
   release:
@@ -20,11 +20,53 @@ jobs:
         run: |
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
-
+      - name: Set up Minikube
+        uses: medyagh/setup-minikube@master
+        with:
+          minikube-version: 'latest'
+          kubernetes-version: 'stable'
+          driver: docker
+      - name: kubectl
+        run: kubectl get pods -A
       - name: Install Helm
         uses: azure/setup-helm@v3
+      - name: Wait for Minikube to be ready
+        run: |
+          minikube status
+          kubectl get nodes
+          kubectl wait --for=condition=Ready node/minikube --timeout=3m
 
-      - name: Run chart-releaser
-        uses: helm/chart-releaser-action@v1.6.0
-        env:
-          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+      - name: Validate Helm template
+        run: |
+          echo "Running Helm template validation..."
+          helm template test-app charts/your-chart -f charts/your-chart/ci/test-values.yaml
+
+      - name: Set PR status
+        if: ${{ failure() }}
+        run: |
+          echo "::error::Helm chart validation failed. Please fix the issues before merging."
+          exit 1
+
+      - name: Perform dry-run Helm installation
+        run: |
+          echo "Performing dry-run Helm installation..."
+          helm upgrade --install test-app charts/your-chart \
+            -f charts/your-chart/ci/test-values.yaml \
+            --create-namespace \
+            --namespace test-namespace \
+            --timeout 1m \
+            --atomic \
+            --dry-run
+
+      - name: Set PR status
+        if: ${{ failure() }}
+        run: |
+          echo "::error::Helm chart validation failed. Please fix the issues before merging."
+          exit 1
+
+
+      # - name: Run chart-releaser
+      #   uses: helm/chart-releaser-action@v1.6.0
+      #   if: success()
+      #   env:
+      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
